/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JiraTestLink;

import org.junit.Test;

import testlink.api.java.client.TestLinkAPIClient;
import testlink.api.java.client.TestLinkAPIException;
import testlink.api.java.client.TestLinkAPIResults;

public class LibraryTest {
	
	public static String DEV_KEY = "30d4fb7305192a917041cd05cbd8ffd2";
	
	//public static String URL = "http://127.0.0.1/testlink/index.php";
	public static String URL = "http://127.0.0.1/testlink/lib/api/xmlrpc/v1/xmlrpc.php";
	
	String testProject = "Jira_001";
	String testPlan = "PLan_001";
	String build = "Build_001";
	String result = null;
	
	@Test
	public void verifyTestLinkResultsUpdated() throws Exception{
		try {
			result = TestLinkAPIResults.TEST_PASSED;			
			updateResultsInTestLink("TC-1", null, result);
		} catch (TestLinkAPIException e) {
			result = TestLinkAPIResults.TEST_FAILED;
			updateResultsInTestLink("TC-1", e.toString(), result);
			e.printStackTrace();
		}
	}
	
	public void updateResultsInTestLink(String testCase, String exception, String result) throws TestLinkAPIException, Exception{
		TestLinkAPIClient testLinkApiClient = new TestLinkAPIClient(DEV_KEY, URL);
		System.out.println(testLinkApiClient.connectErrorMsg);
		testLinkApiClient.reportTestCaseResult(testProject, testPlan, testCase, build, exception, result);
	}
	
}
